name: Lint (actionlint + shellcheck)
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint
        uses: rhysd/actionlint@v1.7.1
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Shellcheck scripts
        run: |
          set -euo pipefail
          shopt -s globstar || true
          shellcheck -s bash scripts/**/*.sh || true
